In [ ]:
import numpy as np

In [ ]:
np.__version__

'2.0.2'

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Excel Food Delivery Project.xlsx to Excel Food Delivery Project.xlsx

In [ ]:
df = pd.read_excel('Excel Food Delivery Project.xlsx')
df

,Customer_id,Gender,Age,City,Order_id,Order_date,Restaurant_name,Dish_Name,Category,Quantity,Price,Payment_method,Order_frequency,Churned,Rating,Delivery_status
0,C6687,OTHER,Adult,Islamabad,O10687,2023-01-09 00:00:00,KFC,Pasta,Italian,3,101.29,Wallet,28,Inactive,3,Delivered
1,C3733,MALE,Adult,Multan,O7733,2023-01-09 00:00:00,Burger King,Sandwich,Continental,4,172.76,Wallet,23,Inactive,5,Delivered
2,C5566,OTHER,Teenager,Islamabad,O9566,2023-01-09 00:00:00,Subway,Pasta,Dessert,5,362.35,Cash,23,Active,5,Delayed
3,C3775,OTHER,Adult,Multan,O7775,2023-01-09 00:00:00,Burger King,Fries,Chinese,2,388.86,Cash,31,Inactive,3,Cancelled
4,C3210,OTHER,Teenager,Karachi,O7210,2023-01-09 00:00:00,Burger King,Pasta,Fast Food,2,528.24,Cash,24,Inactive,4,Delayed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5991,C5821,OTHER,Adult,Peshawar,O9821,9/30/2024,Pizza Hut,Fries,Dessert,2,431.27,Wallet,11,Active,5,Cancelled
5992,C5296,OTHER,Adult,Lahore,O9296,9/30/2024,Pizza Hut,Fries,Fast Food,4,588.11,Cash,42,Inactive,3,Cancelled
5993,C3665,FEMALE,Adult,Islamabad,O7665,9/30/2024,Pizza Hut,Pasta,Fast Food,2,1118.14,Card,27,Active,3,Delayed
5994,C5319,FEMALE,Adult,Lahore,O9319,9/30/2024,Pizza Hut,Pasta,Continental,2,1298.64,Cash,37,Inactive,3,Delivered
5995,C6222,OTHER,Adult,Multan,O10222,9/30/2024,Pizza Hut,Sandwich,Continental,2,1368.66,Cash,16,Inactive,3,Cancelled

In [ ]:
data = df.values
data

array([['C6687', 'OTHER', 'Adult', ..., 'Inactive', 3, 'Delivered'],
       ['C3733', 'MALE', 'Adult', ..., 'Inactive', 5, 'Delivered'],
       ['C5566', 'OTHER', 'Teenager', ..., 'Active', 5, 'Delayed'],
       ...,
       ['C3665', 'FEMALE', 'Adult', ..., 'Active', 3, 'Delayed'],
       ['C5319', 'FEMALE', 'Adult', ..., 'Inactive', 3, 'Delivered'],
       ['C6222', 'OTHER', 'Adult', ..., 'Inactive', 3, 'Cancelled']],
      dtype=object)

In [ ]:
arr = np.array(data)
arr

array([['C6687', 'OTHER', 'Adult', ..., 'Inactive', 3, 'Delivered'],
       ['C3733', 'MALE', 'Adult', ..., 'Inactive', 5, 'Delivered'],
       ['C5566', 'OTHER', 'Teenager', ..., 'Active', 5, 'Delayed'],
       ...,
       ['C3665', 'FEMALE', 'Adult', ..., 'Active', 3, 'Delayed'],
       ['C5319', 'FEMALE', 'Adult', ..., 'Inactive', 3, 'Delivered'],
       ['C6222', 'OTHER', 'Adult', ..., 'Inactive', 3, 'Cancelled']],
      dtype=object)

In [ ]:
arr.shape

(5996, 16)

In [ ]:
arr.ndim

2

In [ ]:
arr[0]

array(['C6687', 'OTHER', 'Adult', 'Islamabad', 'O10687',
       datetime.datetime(2023, 1, 9, 0, 0), 'KFC', 'Pasta', 'Italian', 3,
       101.29, 'Wallet', 28, 'Inactive', 3, 'Delivered'], dtype=object)

In [ ]:
pd.isna(arr).sum().sum()

np.int64(0)

In [ ]:
arr = np.nan_to_num(arr)
arr

array([['C6687', 'OTHER', 'Adult', ..., 'Inactive', 3, 'Delivered'],
       ['C3733', 'MALE', 'Adult', ..., 'Inactive', 5, 'Delivered'],
       ['C5566', 'OTHER', 'Teenager', ..., 'Active', 5, 'Delayed'],
       ...,
       ['C3665', 'FEMALE', 'Adult', ..., 'Active', 3, 'Delayed'],
       ['C5319', 'FEMALE', 'Adult', ..., 'Inactive', 3, 'Delivered'],
       ['C6222', 'OTHER', 'Adult', ..., 'Inactive', 3, 'Cancelled']],
      dtype=object)

In [ ]:
np.mean(arr[:, 10])

np.float64(800.3300833889251)

In [ ]:
np.median(arr[:, 10])

np.float64(805.6800000000001)

In [ ]:
np.std(arr[:, 10])

np.float64(404.8472497934698)

In [ ]:
np.min(arr[:, 10])

100.3

In [ ]:
np.max(arr[:, 10])

1499.95

In [ ]:
arr_price_column = arr[:, 10].astype(float)
arr_price_column

array([7.07319687e-04, 5.17700854e-02, 1.87225378e-01, ...,
       7.27210374e-01, 8.56171186e-01, 9.06197978e-01])

In [ ]:
(
(arr_price_column - np.min(arr_price_column)) /
(np.max(arr_price_column) - np.min(arr_price_column))
)

array([7.07319687e-04, 5.17700854e-02, 1.87225378e-01, ...,
       7.27210374e-01, 8.56171186e-01, 9.06197978e-01])

In [ ]:
arr.reshape(-1, 1)

array([['C6687'],
       ['OTHER'],
       ['Adult'],
       ...,
       ['Inactive'],
       [3],
       ['Cancelled']], dtype=object)

In [ ]:
arr.flatten()

array(['C6687', 'OTHER', 'Adult', ..., 'Inactive', 3, 'Cancelled'],
      dtype=object)

In [ ]:
arr_price_column[arr_price_column > 0]

array([7.07319687e-04, 5.17700854e-02, 1.87225378e-01, ...,
       7.27210374e-01, 8.56171186e-01, 9.06197978e-01])

In [ ]:
np.random.choice(arr.flatten(), size=5)

array(['Wallet', 'KFC', 'Pizza', 'Fast Food', 'Peshawar'], dtype=object)

In [ ]:
np.split(arr, 2)

[array([['C6687', 'OTHER', 'Adult', ..., 'Inactive', 3, 'Delivered'],
        ['C3733', 'MALE', 'Adult', ..., 'Inactive', 5, 'Delivered'],
        ['C5566', 'OTHER', 'Teenager', ..., 'Active', 5, 'Delayed'],
        ...,
        ['C6886', 'OTHER', 'Teenager', ..., 'Inactive', 3, 'Delivered'],
        ['C6745', 'FEMALE', 'Teenager', ..., 'Inactive', 5, 'Cancelled'],
        ['C2695', 'FEMALE', 'Teenager', ..., 'Inactive', 1, 'Delivered']],
       dtype=object),
 array([['C1290', 'MALE', 'Teenager', ..., 'Inactive', 2, 'Delivered'],
        ['C1132', 'MALE', 'Senior', ..., 'Active', 3, 'Delayed'],
        ['C1786', 'OTHER', 'Senior', ..., 'Inactive', 4, 'Delivered'],
        ...,
        ['C3665', 'FEMALE', 'Adult', ..., 'Active', 3, 'Delayed'],
        ['C5319', 'FEMALE', 'Adult', ..., 'Inactive', 3, 'Delivered'],
        ['C6222', 'OTHER', 'Adult', ..., 'Inactive', 3, 'Cancelled']],
       dtype=object)]

In [ ]:
df_new = pd.DataFrame(arr)

In [ ]:
df_new

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,C6687,OTHER,Adult,Islamabad,O10687,2023-01-09 00:00:00,KFC,Pasta,Italian,3,0.000707,Wallet,28,Inactive,3,Delivered
1,C3733,MALE,Adult,Multan,O7733,2023-01-09 00:00:00,Burger King,Sandwich,Continental,4,0.05177,Wallet,23,Inactive,5,Delivered
2,C5566,OTHER,Teenager,Islamabad,O9566,2023-01-09 00:00:00,Subway,Pasta,Dessert,5,0.187225,Cash,23,Active,5,Delayed
3,C3775,OTHER,Adult,Multan,O7775,2023-01-09 00:00:00,Burger King,Fries,Chinese,2,0.206166,Cash,31,Inactive,3,Cancelled
4,C3210,OTHER,Teenager,Karachi,O7210,2023-01-09 00:00:00,Burger King,Pasta,Fast Food,2,0.305748,Cash,24,Inactive,4,Delayed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5991,C5821,OTHER,Adult,Peshawar,O9821,9/30/2024,Pizza Hut,Fries,Dessert,2,0.236466,Wallet,11,Active,5,Cancelled
5992,C5296,OTHER,Adult,Lahore,O9296,9/30/2024,Pizza Hut,Fries,Fast Food,4,0.348523,Cash,42,Inactive,3,Cancelled
5993,C3665,FEMALE,Adult,Islamabad,O7665,9/30/2024,Pizza Hut,Pasta,Fast Food,2,0.72721,Card,27,Active,3,Delayed
5994,C5319,FEMALE,Adult,Lahore,O9319,9/30/2024,Pizza Hut,Pasta,Continental,2,0.856171,Cash,37,Inactive,3,Delivered
5995,C6222,OTHER,Adult,Multan,O10222,9/30/2024,Pizza Hut,Sandwich,Continental,2,0.906198,Cash,16,Inactive,3,Cancelled

In [ ]:
arr[:, 5] = pd.to_datetime(arr[:, 5], errors='coerce').normalize().values

In [ ]:
print(arr)

[['C6687' 'OTHER' 'Adult' ... 'Inactive' 3 'Delivered']
 ['C3733' 'MALE' 'Adult' ... 'Inactive' 5 'Delivered']
 ['C5566' 'OTHER' 'Teenager' ... 'Active' 5 'Delayed']
 ...
 ['C3665' 'FEMALE' 'Adult' ... 'Active' 3 'Delayed']
 ['C5319' 'FEMALE' 'Adult' ... 'Inactive' 3 'Delivered']
 ['C6222' 'OTHER' 'Adult' ... 'Inactive' 3 'Cancelled']]