In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel('/content/Excel Food Delivery Project.xlsx')

In [ ]:
df

,Customer_id,Gender,Age,City,Order_id,Order_date,Restaurant_name,Dish_Name,Category,Quantity,Price,Payment_method,Order_frequency,Churned,Rating,Delivery_status
0,C6687,OTHER,Adult,Islamabad,O10687,2023-01-09 00:00:00,KFC,Pasta,Italian,3,101.29,Wallet,28,Inactive,3,Delivered
1,C3733,MALE,Adult,Multan,O7733,2023-01-09 00:00:00,Burger King,Sandwich,Continental,4,172.76,Wallet,23,Inactive,5,Delivered
2,C5566,OTHER,Teenager,Islamabad,O9566,2023-01-09 00:00:00,Subway,Pasta,Dessert,5,362.35,Cash,23,Active,5,Delayed
3,C3775,OTHER,Adult,Multan,O7775,2023-01-09 00:00:00,Burger King,Fries,Chinese,2,388.86,Cash,31,Inactive,3,Cancelled
4,C3210,OTHER,Teenager,Karachi,O7210,2023-01-09 00:00:00,Burger King,Pasta,Fast Food,2,528.24,Cash,24,Inactive,4,Delayed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5991,C5821,OTHER,Adult,Peshawar,O9821,9/30/2024,Pizza Hut,Fries,Dessert,2,431.27,Wallet,11,Active,5,Cancelled
5992,C5296,OTHER,Adult,Lahore,O9296,9/30/2024,Pizza Hut,Fries,Fast Food,4,588.11,Cash,42,Inactive,3,Cancelled
5993,C3665,FEMALE,Adult,Islamabad,O7665,9/30/2024,Pizza Hut,Pasta,Fast Food,2,1118.14,Card,27,Active,3,Delayed
5994,C5319,FEMALE,Adult,Lahore,O9319,9/30/2024,Pizza Hut,Pasta,Continental,2,1298.64,Cash,37,Inactive,3,Delivered
5995,C6222,OTHER,Adult,Multan,O10222,9/30/2024,Pizza Hut,Sandwich,Continental,2,1368.66,Cash,16,Inactive,3,Cancelled

In [ ]:
df.head()

,Customer_id,Gender,Age,City,Order_id,Order_date,Restaurant_name,Dish_Name,Category,Quantity,Price,Payment_method,Order_frequency,Churned,Rating,Delivery_status
0,C6687,OTHER,Adult,Islamabad,O10687,2023-01-09 00:00:00,KFC,Pasta,Italian,3,101.29,Wallet,28,Inactive,3,Delivered
1,C3733,MALE,Adult,Multan,O7733,2023-01-09 00:00:00,Burger King,Sandwich,Continental,4,172.76,Wallet,23,Inactive,5,Delivered
2,C5566,OTHER,Teenager,Islamabad,O9566,2023-01-09 00:00:00,Subway,Pasta,Dessert,5,362.35,Cash,23,Active,5,Delayed
3,C3775,OTHER,Adult,Multan,O7775,2023-01-09 00:00:00,Burger King,Fries,Chinese,2,388.86,Cash,31,Inactive,3,Cancelled
4,C3210,OTHER,Teenager,Karachi,O7210,2023-01-09 00:00:00,Burger King,Pasta,Fast Food,2,528.24,Cash,24,Inactive,4,Delayed

In [ ]:
df.tail()

,Customer_id,Gender,Age,City,Order_id,Order_date,Restaurant_name,Dish_Name,Category,Quantity,Price,Payment_method,Order_frequency,Churned,Rating,Delivery_status
5991,C5821,OTHER,Adult,Peshawar,O9821,9/30/2024,Pizza Hut,Fries,Dessert,2,431.27,Wallet,11,Active,5,Cancelled
5992,C5296,OTHER,Adult,Lahore,O9296,9/30/2024,Pizza Hut,Fries,Fast Food,4,588.11,Cash,42,Inactive,3,Cancelled
5993,C3665,FEMALE,Adult,Islamabad,O7665,9/30/2024,Pizza Hut,Pasta,Fast Food,2,1118.14,Card,27,Active,3,Delayed
5994,C5319,FEMALE,Adult,Lahore,O9319,9/30/2024,Pizza Hut,Pasta,Continental,2,1298.64,Cash,37,Inactive,3,Delivered
5995,C6222,OTHER,Adult,Multan,O10222,9/30/2024,Pizza Hut,Sandwich,Continental,2,1368.66,Cash,16,Inactive,3,Cancelled

In [ ]:
df.head(3)

,Customer_id,Gender,Age,City,Order_id,Order_date,Restaurant_name,Dish_Name,Category,Quantity,Price,Payment_method,Order_frequency,Churned,Rating,Delivery_status
0,C6687,OTHER,Adult,Islamabad,O10687,2023-01-09 00:00:00,KFC,Pasta,Italian,3,101.29,Wallet,28,Inactive,3,Delivered
1,C3733,MALE,Adult,Multan,O7733,2023-01-09 00:00:00,Burger King,Sandwich,Continental,4,172.76,Wallet,23,Inactive,5,Delivered
2,C5566,OTHER,Teenager,Islamabad,O9566,2023-01-09 00:00:00,Subway,Pasta,Dessert,5,362.35,Cash,23,Active,5,Delayed

In [ ]:
df.tail(3)

,Customer_id,Gender,Age,City,Order_id,Order_date,Restaurant_name,Dish_Name,Category,Quantity,Price,Payment_method,Order_frequency,Churned,Rating,Delivery_status
5993,C3665,FEMALE,Adult,Islamabad,O7665,9/30/2024,Pizza Hut,Pasta,Fast Food,2,1118.14,Card,27,Active,3,Delayed
5994,C5319,FEMALE,Adult,Lahore,O9319,9/30/2024,Pizza Hut,Pasta,Continental,2,1298.64,Cash,37,Inactive,3,Delivered
5995,C6222,OTHER,Adult,Multan,O10222,9/30/2024,Pizza Hut,Sandwich,Continental,2,1368.66,Cash,16,Inactive,3,Cancelled

In [ ]:
df.shape

(5996, 16)

In [ ]:
df.columns

Index(['Customer_id', 'Gender', 'Age', 'City', 'Order_id', 'Order_date',
       'Restaurant_name', 'Dish_Name', 'Category', 'Quantity', 'Price',
       'Payment_method', 'Order_frequency', 'Churned', 'Rating',
       'Delivery_status'],
      dtype='object')

In [ ]:
df.dtypes

Customer_id         object
Gender              object
Age                 object
City                object
Order_id            object
Order_date          object
Restaurant_name     object
Dish_Name           object
Category            object
Quantity             int64
Price              float64
Payment_method      object
Order_frequency      int64
Churned             object
Rating               int64
Delivery_status     object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5996 entries, 0 to 5995
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Customer_id      5996 non-null   object
 1   Gender           5996 non-null   object
 2   Age              5996 non-null   object
 3   City             5996 non-null   object
 4   Order_id         5996 non-null   object
 5   Order_date       5996 non-null   object
 6   Restaurant_name  5996 non-null   object
 7   Dish_Name        5996 non-null   object
 8   Category         5996 non-null   object
 9   Quantity         5996 non-null   int64
 10  Price            5996 non-null   float64
 11  Payment_method   5996 non-null   object
 12  Order_frequency  5996 non-null   int64
 13  Churned          5996 non-null   object
 14  Rating           5996 non-null   int64
 15  Delivery_status  5996 non-null   object
dtypes: float64(1), int64(3), object(12)
memory usage: 749.6+ KB

In [ ]:
df.describe()

          Quantity        Price  Order_frequency       Rating
count  5996.000000  5996.000000      5996.000000  5996.000000
mean      2.992161   800.330083        25.298699     2.998165
std       1.414840   404.881014        14.355152     1.405635
min       1.000000   100.300000         1.000000     1.000000
25%       2.000000   440.720000        13.000000     2.000000
50%       3.000000   805.680000        25.000000     3.000000
75%       4.000000  1149.737500        37.000000     4.000000
max       5.000000  1499.950000        50.000000     5.000000

In [ ]:
df.isnull().sum()

Customer_id        0
Gender             0
Age                0
City               0
Order_id           0
Order_date         0
Restaurant_name    0
Dish_Name          0
Category           0
Quantity           0
Price              0
Payment_method     0
Order_frequency    0
Churned            0
Rating             0
Delivery_status    0
dtype: int64

In [ ]:
df.fillna(method='ffill', inplace=True)

/tmp/ipykernel_7208/3970806690.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', inplace=True)

In [ ]:
df.dropna(inplace=True)
df

,Customer_id,Gender,Age,City,Order_id,Order_date,Restaurant_name,Dish_Name,Category,Quantity,Price,Payment_method,Order_frequency,Churned,Rating,Delivery_status
0,C6687,OTHER,Adult,Islamabad,O10687,2023-01-09 00:00:00,KFC,Pasta,Italian,3,101.29,Wallet,28,Inactive,3,Delivered
1,C3733,MALE,Adult,Multan,O7733,2023-01-09 00:00:00,Burger King,Sandwich,Continental,4,172.76,Wallet,23,Inactive,5,Delivered
2,C5566,OTHER,Teenager,Islamabad,O9566,2023-01-09 00:00:00,Subway,Pasta,Dessert,5,362.35,Cash,23,Active,5,Delayed
3,C3775,OTHER,Adult,Multan,O7775,2023-01-09 00:00:00,Burger King,Fries,Chinese,2,388.86,Cash,31,Inactive,3,Cancelled
4,C3210,OTHER,Teenager,Karachi,O7210,2023-01-09 00:00:00,Burger King,Pasta,Fast Food,2,528.24,Cash,24,Inactive,4,Delayed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5991,C5821,OTHER,Adult,Peshawar,O9821,9/30/2024,Pizza Hut,Fries,Dessert,2,431.27,Wallet,11,Active,5,Cancelled
5992,C5296,OTHER,Adult,Lahore,O9296,9/30/2024,Pizza Hut,Fries,Fast Food,4,588.11,Cash,42,Inactive,3,Cancelled
5993,C3665,FEMALE,Adult,Islamabad,O7665,9/30/2024,Pizza Hut,Pasta,Fast Food,2,1118.14,Card,27,Active,3,Delayed
5994,C5319,FEMALE,Adult,Lahore,O9319,9/30/2024,Pizza Hut,Pasta,Continental,2,1298.64,Cash,37,Inactive,3,Delivered
5995,C6222,OTHER,Adult,Multan,O10222,9/30/2024,Pizza Hut,Sandwich,Continental,2,1368.66,Cash,16,Inactive,3,Cancelled

In [ ]:
df.drop_duplicates(inplace=True)
df

,Customer_id,Gender,Age,City,Order_id,Order_date,Restaurant_name,Dish_Name,Category,Quantity,Price,Payment_method,Order_frequency,Churned,Rating,Delivery_status
0,C6687,OTHER,Adult,Islamabad,O10687,2023-01-09 00:00:00,KFC,Pasta,Italian,3,101.29,Wallet,28,Inactive,3,Delivered
1,C3733,MALE,Adult,Multan,O7733,2023-01-09 00:00:00,Burger King,Sandwich,Continental,4,172.76,Wallet,23,Inactive,5,Delivered
2,C5566,OTHER,Teenager,Islamabad,O9566,2023-01-09 00:00:00,Subway,Pasta,Dessert,5,362.35,Cash,23,Active,5,Delayed
3,C3775,OTHER,Adult,Multan,O7775,2023-01-09 00:00:00,Burger King,Fries,Chinese,2,388.86,Cash,31,Inactive,3,Cancelled
4,C3210,OTHER,Teenager,Karachi,O7210,2023-01-09 00:00:00,Burger King,Pasta,Fast Food,2,528.24,Cash,24,Inactive,4,Delayed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5991,C5821,OTHER,Adult,Peshawar,O9821,9/30/2024,Pizza Hut,Fries,Dessert,2,431.27,Wallet,11,Active,5,Cancelled
5992,C5296,OTHER,Adult,Lahore,O9296,9/30/2024,Pizza Hut,Fries,Fast Food,4,588.11,Cash,42,Inactive,3,Cancelled
5993,C3665,FEMALE,Adult,Islamabad,O7665,9/30/2024,Pizza Hut,Pasta,Fast Food,2,1118.14,Card,27,Active,3,Delayed
5994,C5319,FEMALE,Adult,Lahore,O9319,9/30/2024,Pizza Hut,Pasta,Continental,2,1298.64,Cash,37,Inactive,3,Delivered
5995,C6222,OTHER,Adult,Multan,O10222,9/30/2024,Pizza Hut,Sandwich,Continental,2,1368.66,Cash,16,Inactive,3,Cancelled

In [ ]:
df.columns = df.columns.str.lower().str.replace(" ", "_")
df

,customer_id,gender,age,city,order_id,order_date,restaurant_name,dish_name,category,quantity,price,payment_method,order_frequency,churned,rating,delivery_status
0,C6687,OTHER,Adult,Islamabad,O10687,2023-01-09 00:00:00,KFC,Pasta,Italian,3,101.29,Wallet,28,Inactive,3,Delivered
1,C3733,MALE,Adult,Multan,O7733,2023-01-09 00:00:00,Burger King,Sandwich,Continental,4,172.76,Wallet,23,Inactive,5,Delivered
2,C5566,OTHER,Teenager,Islamabad,O9566,2023-01-09 00:00:00,Subway,Pasta,Dessert,5,362.35,Cash,23,Active,5,Delayed
3,C3775,OTHER,Adult,Multan,O7775,2023-01-09 00:00:00,Burger King,Fries,Chinese,2,388.86,Cash,31,Inactive,3,Cancelled
4,C3210,OTHER,Teenager,Karachi,O7210,2023-01-09 00:00:00,Burger King,Pasta,Fast Food,2,528.24,Cash,24,Inactive,4,Delayed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5991,C5821,OTHER,Adult,Peshawar,O9821,9/30/2024,Pizza Hut,Fries,Dessert,2,431.27,Wallet,11,Active,5,Cancelled
5992,C5296,OTHER,Adult,Lahore,O9296,9/30/2024,Pizza Hut,Fries,Fast Food,4,588.11,Cash,42,Inactive,3,Cancelled
5993,C3665,FEMALE,Adult,Islamabad,O7665,9/30/2024,Pizza Hut,Pasta,Fast Food,2,1118.14,Card,27,Active,3,Delayed
5994,C5319,FEMALE,Adult,Lahore,O9319,9/30/2024,Pizza Hut,Pasta,Continental,2,1298.64,Cash,37,Inactive,3,Delivered
5995,C6222,OTHER,Adult,Multan,O10222,9/30/2024,Pizza Hut,Sandwich,Continental,2,1368.66,Cash,16,Inactive,3,Cancelled

In [ ]:
df['order_date'] = pd.to_datetime(df['order_date'])
df

,customer_id,gender,age,city,order_id,order_date,restaurant_name,dish_name,category,quantity,price,payment_method,order_frequency,churned,rating,delivery_status
0,C6687,OTHER,Adult,Islamabad,O10687,2023-01-09,KFC,Pasta,Italian,3,101.29,Wallet,28,Inactive,3,Delivered
1,C3733,MALE,Adult,Multan,O7733,2023-01-09,Burger King,Sandwich,Continental,4,172.76,Wallet,23,Inactive,5,Delivered
2,C5566,OTHER,Teenager,Islamabad,O9566,2023-01-09,Subway,Pasta,Dessert,5,362.35,Cash,23,Active,5,Delayed
3,C3775,OTHER,Adult,Multan,O7775,2023-01-09,Burger King,Fries,Chinese,2,388.86,Cash,31,Inactive,3,Cancelled
4,C3210,OTHER,Teenager,Karachi,O7210,2023-01-09,Burger King,Pasta,Fast Food,2,528.24,Cash,24,Inactive,4,Delayed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5991,C5821,OTHER,Adult,Peshawar,O9821,2024-09-30,Pizza Hut,Fries,Dessert,2,431.27,Wallet,11,Active,5,Cancelled
5992,C5296,OTHER,Adult,Lahore,O9296,2024-09-30,Pizza Hut,Fries,Fast Food,4,588.11,Cash,42,Inactive,3,Cancelled
5993,C3665,FEMALE,Adult,Islamabad,O7665,2024-09-30,Pizza Hut,Pasta,Fast Food,2,1118.14,Card,27,Active,3,Delayed
5994,C5319,FEMALE,Adult,Lahore,O9319,2024-09-30,Pizza Hut,Pasta,Continental,2,1298.64,Cash,37,Inactive,3,Delivered
5995,C6222,OTHER,Adult,Multan,O10222,2024-09-30,Pizza Hut,Sandwich,Continental,2,1368.66,Cash,16,Inactive,3,Cancelled

In [ ]:
df = df[df['rating'] > 3]
df

,customer_id,gender,age,city,order_id,order_date,restaurant_name,dish_name,category,quantity,price,payment_method,order_frequency,churned,rating,delivery_status
1,C3733,MALE,Adult,Multan,O7733,2023-01-09,Burger King,Sandwich,Continental,4,172.76,Wallet,23,Inactive,5,Delivered
2,C5566,OTHER,Teenager,Islamabad,O9566,2023-01-09,Subway,Pasta,Dessert,5,362.35,Cash,23,Active,5,Delayed
4,C3210,OTHER,Teenager,Karachi,O7210,2023-01-09,Burger King,Pasta,Fast Food,2,528.24,Cash,24,Inactive,4,Delayed
8,C1871,MALE,Adult,Multan,O5871,2023-01-10,KFC,Fries,Chinese,4,539.86,Wallet,28,Active,4,Delayed
13,C1888,OTHER,Adult,Multan,O5888,2023-01-10,KFC,Pasta,Chinese,5,1472.72,Wallet,49,Active,4,Delayed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5986,C2596,FEMALE,Teenager,Lahore,O6596,2023-09-30,KFC,Pasta,Continental,2,902.10,Card,25,Active,5,Delivered
5987,C4165,MALE,Senior,Karachi,O8165,2023-09-30,McDonald's,Pasta,Continental,2,1378.13,Card,6,Active,5,Delayed
5988,C3987,MALE,Adult,Lahore,O7987,2023-09-30,Pizza Hut,Pizza,Dessert,4,1450.30,Wallet,39,Inactive,4,Delivered
5990,C2785,MALE,Senior,Karachi,O6785,2024-09-30,Pizza Hut,Sandwich,Dessert,3,186.46,Card,42,Active,5,Delayed
5991,C5821,OTHER,Adult,Peshawar,O9821,2024-09-30,Pizza Hut,Fries,Dessert,2,431.27,Wallet,11,Active,5,Cancelled

In [ ]:
df.sort_values(by='delivery_status', inplace=True)
df

,customer_id,gender,age,city,order_id,order_date,restaurant_name,dish_name,category,quantity,price,payment_method,order_frequency,churned,rating,delivery_status
5991,C5821,OTHER,Adult,Peshawar,O9821,2024-09-30,Pizza Hut,Fries,Dessert,2,431.27,Wallet,11,Active,5,Cancelled
4205,C2552,FEMALE,Adult,Peshawar,O6552,2024-04-15,Burger King,Pasta,Continental,5,1441.98,Card,13,Inactive,4,Cancelled
1851,C5135,OTHER,Teenager,Peshawar,O9135,2025-05-08,Subway,Sandwich,Fast Food,2,917.14,Cash,44,Active,4,Cancelled
1854,C3964,OTHER,Teenager,Karachi,O7964,2025-05-08,Pizza Hut,Burger,Continental,5,1222.24,Cash,22,Inactive,5,Cancelled
1855,C6294,OTHER,Adult,Multan,O10294,2025-05-08,Pizza Hut,Burger,Italian,3,1273.04,Cash,39,Active,5,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4277,C3916,OTHER,Teenager,Islamabad,O7916,2025-04-20,KFC,Pasta,Continental,2,226.30,Card,16,Active,4,Delivered
1836,C1765,OTHER,Senior,Peshawar,O5765,2025-05-06,Subway,Sandwich,Italian,4,1060.12,Wallet,34,Active,4,Delivered
4219,C4181,FEMALE,Adult,Multan,O8181,2024-04-16,Subway,Fries,Italian,5,433.26,Card,16,Active,5,Delivered
4230,C5635,MALE,Senior,Islamabad,O9635,2024-04-17,Pizza Hut,Fries,Chinese,3,582.57,Wallet,41,Inactive,5,Delivered
1,C3733,MALE,Adult,Multan,O7733,2023-01-09,Burger King,Sandwich,Continental,4,172.76,Wallet,23,Inactive,5,Delivered

In [ ]:
df.groupby('city')['delivery_status'].value_counts()
df

,customer_id,gender,age,city,order_id,order_date,restaurant_name,dish_name,category,quantity,price,payment_method,order_frequency,churned,rating,delivery_status
5991,C5821,OTHER,Adult,Peshawar,O9821,2024-09-30,Pizza Hut,Fries,Dessert,2,431.27,Wallet,11,Active,5,Cancelled
4205,C2552,FEMALE,Adult,Peshawar,O6552,2024-04-15,Burger King,Pasta,Continental,5,1441.98,Card,13,Inactive,4,Cancelled
1851,C5135,OTHER,Teenager,Peshawar,O9135,2025-05-08,Subway,Sandwich,Fast Food,2,917.14,Cash,44,Active,4,Cancelled
1854,C3964,OTHER,Teenager,Karachi,O7964,2025-05-08,Pizza Hut,Burger,Continental,5,1222.24,Cash,22,Inactive,5,Cancelled
1855,C6294,OTHER,Adult,Multan,O10294,2025-05-08,Pizza Hut,Burger,Italian,3,1273.04,Cash,39,Active,5,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4277,C3916,OTHER,Teenager,Islamabad,O7916,2025-04-20,KFC,Pasta,Continental,2,226.30,Card,16,Active,4,Delivered
1836,C1765,OTHER,Senior,Peshawar,O5765,2025-05-06,Subway,Sandwich,Italian,4,1060.12,Wallet,34,Active,4,Delivered
4219,C4181,FEMALE,Adult,Multan,O8181,2024-04-16,Subway,Fries,Italian,5,433.26,Card,16,Active,5,Delivered
4230,C5635,MALE,Senior,Islamabad,O9635,2024-04-17,Pizza Hut,Fries,Chinese,3,582.57,Wallet,41,Inactive,5,Delivered
1,C3733,MALE,Adult,Multan,O7733,2023-01-09,Burger King,Sandwich,Continental,4,172.76,Wallet,23,Inactive,5,Delivered

In [ ]:
df['month'] = df['order_date'].dt.month
df

,customer_id,gender,age,city,order_id,order_date,restaurant_name,dish_name,category,quantity,price,payment_method,order_frequency,churned,rating,delivery_status,month
5991,C5821,OTHER,Adult,Peshawar,O9821,2024-09-30,Pizza Hut,Fries,Dessert,2,431.27,Wallet,11,Active,5,Cancelled,9
4205,C2552,FEMALE,Adult,Peshawar,O6552,2024-04-15,Burger King,Pasta,Continental,5,1441.98,Card,13,Inactive,4,Cancelled,4
1851,C5135,OTHER,Teenager,Peshawar,O9135,2025-05-08,Subway,Sandwich,Fast Food,2,917.14,Cash,44,Active,4,Cancelled,5
1854,C3964,OTHER,Teenager,Karachi,O7964,2025-05-08,Pizza Hut,Burger,Continental,5,1222.24,Cash,22,Inactive,5,Cancelled,5
1855,C6294,OTHER,Adult,Multan,O10294,2025-05-08,Pizza Hut,Burger,Italian,3,1273.04,Cash,39,Active,5,Cancelled,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4277,C3916,OTHER,Teenager,Islamabad,O7916,2025-04-20,KFC,Pasta,Continental,2,226.30,Card,16,Active,4,Delivered,4
1836,C1765,OTHER,Senior,Peshawar,O5765,2025-05-06,Subway,Sandwich,Italian,4,1060.12,Wallet,34,Active,4,Delivered,5
4219,C4181,FEMALE,Adult,Multan,O8181,2024-04-16,Subway,Fries,Italian,5,433.26,Card,16,Active,5,Delivered,4
4230,C5635,MALE,Senior,Islamabad,O9635,2024-04-17,Pizza Hut,Fries,Chinese,3,582.57,Wallet,41,Inactive,5,Delivered,4
1,C3733,MALE,Adult,Multan,O7733,2023-01-09,Burger King,Sandwich,Continental,4,172.76,Wallet,23,Inactive,5,Delivered,1

In [ ]:
df = pd.get_dummies(df, columns=['city'])
df

,customer_id,gender,age,order_id,order_date,restaurant_name,dish_name,category,quantity,price,...,order_frequency,churned,rating,delivery_status,month,city_Islamabad,city_Karachi,city_Lahore,city_Multan,city_Peshawar
5991,C5821,OTHER,Adult,O9821,2024-09-30,Pizza Hut,Fries,Dessert,2,431.27,...,11,Active,5,Cancelled,9,False,False,False,False,True
4205,C2552,FEMALE,Adult,O6552,2024-04-15,Burger King,Pasta,Continental,5,1441.98,...,13,Inactive,4,Cancelled,4,False,False,False,False,True
1851,C5135,OTHER,Teenager,O9135,2025-05-08,Subway,Sandwich,Fast Food,2,917.14,...,44,Active,4,Cancelled,5,False,False,False,False,True
1854,C3964,OTHER,Teenager,O7964,2025-05-08,Pizza Hut,Burger,Continental,5,1222.24,...,22,Inactive,5,Cancelled,5,False,True,False,False,False
1855,C6294,OTHER,Adult,O10294,2025-05-08,Pizza Hut,Burger,Italian,3,1273.04,...,39,Active,5,Cancelled,5,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4277,C3916,OTHER,Teenager,O7916,2025-04-20,KFC,Pasta,Continental,2,226.30,...,16,Active,4,Delivered,4,True,False,False,False,False
1836,C1765,OTHER,Senior,O5765,2025-05-06,Subway,Sandwich,Italian,4,1060.12,...,34,Active,4,Delivered,5,False,False,False,False,True
4219,C4181,FEMALE,Adult,O8181,2024-04-16,Subway,Fries,Italian,5,433.26,...,16,Active,5,Delivered,4,False,False,False,True,False
4230,C5635,MALE,Senior,O9635,2024-04-17,Pizza Hut,Fries,Chinese,3,582.57,...,41,Inactive,5,Delivered,4,True,False,False,False,False
1,C3733,MALE,Adult,O7733,2023-01-09,Burger King,Sandwich,Continental,4,172.76,...,23,Inactive,5,Delivered,1,False,False,False,True,False

In [ ]:
df.drop(['order_id'], axis=0, inplace=True, errors='ignore')
df

,customer_id,gender,age,order_date,restaurant_name,dish_name,category,quantity,price,payment_method,order_frequency,churned,rating,delivery_status,month,city_Islamabad,city_Karachi,city_Lahore,city_Multan,city_Peshawar
5991,C5821,OTHER,Adult,2024-09-30,Pizza Hut,Fries,Dessert,2,431.27,Wallet,11,Active,5,Cancelled,9,False,False,False,False,True
4205,C2552,FEMALE,Adult,2024-04-15,Burger King,Pasta,Continental,5,1441.98,Card,13,Inactive,4,Cancelled,4,False,False,False,False,True
1851,C5135,OTHER,Teenager,2025-05-08,Subway,Sandwich,Fast Food,2,917.14,Cash,44,Active,4,Cancelled,5,False,False,False,False,True
1854,C3964,OTHER,Teenager,2025-05-08,Pizza Hut,Burger,Continental,5,1222.24,Cash,22,Inactive,5,Cancelled,5,False,True,False,False,False
1855,C6294,OTHER,Adult,2025-05-08,Pizza Hut,Burger,Italian,3,1273.04,Cash,39,Active,5,Cancelled,5,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4277,C3916,OTHER,Teenager,2025-04-20,KFC,Pasta,Continental,2,226.30,Card,16,Active,4,Delivered,4,True,False,False,False,False
1836,C1765,OTHER,Senior,2025-05-06,Subway,Sandwich,Italian,4,1060.12,Wallet,34,Active,4,Delivered,5,False,False,False,False,True
4219,C4181,FEMALE,Adult,2024-04-16,Subway,Fries,Italian,5,433.26,Card,16,Active,5,Delivered,4,False,False,False,True,False
4230,C5635,MALE,Senior,2024-04-17,Pizza Hut,Fries,Chinese,3,582.57,Wallet,41,Inactive,5,Delivered,4,True,False,False,False,False
1,C3733,MALE,Adult,2023-01-09,Burger King,Sandwich,Continental,4,172.76,Wallet,23,Inactive,5,Delivered,1,False,False,False,True,False

In [ ]:
df.to_csv('/content/cleaned_data.csv', index=False)
df

,customer_id,gender,age,order_date,restaurant_name,dish_name,category,quantity,price,payment_method,order_frequency,churned,rating,delivery_status,month,city_Islamabad,city_Karachi,city_Lahore,city_Multan,city_Peshawar
5991,C5821,OTHER,Adult,2024-09-30,Pizza Hut,Fries,Dessert,2,431.27,Wallet,11,Active,5,Cancelled,9,False,False,False,False,True
4205,C2552,FEMALE,Adult,2024-04-15,Burger King,Pasta,Continental,5,1441.98,Card,13,Inactive,4,Cancelled,4,False,False,False,False,True
1851,C5135,OTHER,Teenager,2025-05-08,Subway,Sandwich,Fast Food,2,917.14,Cash,44,Active,4,Cancelled,5,False,False,False,False,True
1854,C3964,OTHER,Teenager,2025-05-08,Pizza Hut,Burger,Continental,5,1222.24,Cash,22,Inactive,5,Cancelled,5,False,True,False,False,False
1855,C6294,OTHER,Adult,2025-05-08,Pizza Hut,Burger,Italian,3,1273.04,Cash,39,Active,5,Cancelled,5,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4277,C3916,OTHER,Teenager,2025-04-20,KFC,Pasta,Continental,2,226.30,Card,16,Active,4,Delivered,4,True,False,False,False,False
1836,C1765,OTHER,Senior,2025-05-06,Subway,Sandwich,Italian,4,1060.12,Wallet,34,Active,4,Delivered,5,False,False,False,False,True
4219,C4181,FEMALE,Adult,2024-04-16,Subway,Fries,Italian,5,433.26,Card,16,Active,5,Delivered,4,False,False,False,True,False
4230,C5635,MALE,Senior,2024-04-17,Pizza Hut,Fries,Chinese,3,582.57,Wallet,41,Inactive,5,Delivered,4,True,False,False,False,False
1,C3733,MALE,Adult,2023-01-09,Burger King,Sandwich,Continental,4,172.76,Wallet,23,Inactive,5,Delivered,1,False,False,False,True,False